### ISSUE TITLE
Add support for sparse indexes

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#18]
# Proposed
When parsing entity indexes, allow for [sparse indexes](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-indexes-general-sparse-indexes.html)

I.e
for Index with `sortKey: PUB_ID#${id}` do not auto parse, when index is marked as `sparse index`

## Implementation 
- [x] Add sparse index option on @Entity -> indexes (ideally isSparse: boolean)  
- [x] Allow optional values when parsing `sparse` marked key
- [x] If parsing an sparse index and referenced variable is missing value, DO NOT ADD partition or sort key attributes for that index

**Comment by michael-pont** [comment]
Hi @whimzyLive 
Just wanted to understand the exact behavior of isSparse
From documentation:
```
(property) isSparse?: boolean
DynamoDB only adds item to index if both Partition Key and Sort Key defined for any given GSI contains value

Indexes missing sort key value will not be added to index.
```

However, when I define false for a sparseIndex I expect undefined/optional values to be allowed for sort key
```
    GSI2: {
      partitionKey: 'COMPANY#{{companyId}}',
      sortKey: 'DEPT#{{deptId}}',
      type: INDEX_TYPE.GSI,
      isSparse: false,
    },

...
  @Attribute()
  companyId: string;

  @Attribute()
  deptId?: string;
...
```
This is not working though when I try to create a new user with companyId defined but deptId empty.
I get the following error:
```
"deptId" was referenced in DEPT#{
    {deptId
    }
} but it's value could not be resolved.
```
Additionally, if i define a default value for deptId, the same error occurs, so it appears as if the code [here](https://github.com/typedorm/typedorm/blob/7c3e64a58e7029eb20f089c2aa0b2ccf31a53563/packages/core/src/helpers/parse-key.ts) is running before default value is set.
```
  @Attribute({
    default: '',
  })
  deptId?: string;
```
So my question is what exactly is the expected behavior when isSparse: false?

**Comment by michael-pont** [comment]
As a followup to my previous comment, I observed the opposite behavior with the same entity but a different index:
```
    GSI3: {
      partitionKey: 'COMPANY#{{companyId}}',
      sortKey: {
        alias: 'officeStatus',
      },
      type: INDEX_TYPE.GSI,
    },

...
  @Attribute({
    default: OfficeStatus.REMOTE,
  })
  officeStatus: OfficeStatus;
...
```
When I create a user and leave officeStatus undefined it will create the default value for me and will not throw any error like the one from the previous comment. Querying then with PK = companyId and officeStatus = remote works and returns users

**Comment by structurr** [comment]
I'm running into the same issue as @michael-pont mentioned above. Please allow sort keys to be optional when defining GSIs on a table.
