### ISSUE TITLE
Publish TypeDORM packages in ESM & CJS instead of UMD 

### ISSUE THREAD

**Issue by aldex32** [typedorm/typedorm#220]
Hello,

I am trying to use this nice library in some AWS lambda functions, but I am facing issues with bundling with both esbuild and webpack. Webpack is complaining with: 
```
WARNING in ./node_modules/@typedorm/common/index.js 13:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
What is the reason of publishing this library as UMD?

**Comment by whimzyLive** [comment]
We publish all the modules of this library in UMD so that they can be used in both Nodejs and Browser environments. (cjs and amd).

Can you provide more information in which specific version of TypeDORM you are seeing this warning?

On a side note, This library uses reflections to get the read the types at runtime which I (remember) does not correctly get emitted by esbuild. May be have a look at [this](https://github.com/evanw/esbuild/issues/257).

**Comment by aldex32** [comment]
The version which I am using is:
```
"@typedorm/common": "^1.14.9",
"@typedorm/core": "^1.14.9",
```

I know that esbuild does not support TS decorators, but even doing tsc separately before esbuild that still doesn't work:
```
Error: Cannot find module '@typedorm/common/public-api'
```
Same problem with webpack, still not having success.

**Comment by aldex32** [comment]
It's a bit related with this [issue](https://github.com/typedorm/typedorm/issues/201)

**Comment by whimzyLive** [comment]
can you try [this](https://github.com/typedorm/typedorm/issues/201#issuecomment-1019356153)

**Comment by whimzyLive** [comment]
Perhaps, are you able to create a small repro for me to have a look at? 
This does sound somewhat familiar, but need to confirm if it is related to one of the other issues.

**Comment by aukevanleeuwen** [comment]
Thanks for you quick response, and the library in general.

> We publish all the modules of this library in UMD so that they can be used in both Nodejs and Browser environments. (cjs and amd).

If I may be so blunt: isn't that a bit of an old way of thinking about it? By publishing like this you're essentially making your code un-bundle-able by commonly used bundlers such as `esbuild`, `swc`, `rollup`, `...`. Webpack does it's very best but is issues a gazillion `Critical` warnings such as `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`.

I would argue that:
1. Currently used browsers are more than capable of support ESM as an output format. https://caniuse.com/es6-module. Earliest implementations are from `2017`: https://jakearchibald.com/2017/es-modules-in-browsers/ which is 5 years ago.
2. Nowadays people that are using these kind of libraries in their webapps are inclined to use bundlers such as the earlier mentioned ones. It's the problem of the _user_ of this library to make sure that the platform that he/she wants to use it in actually supports it. Basically the output target of those bundlers is what matters then right and you don't have to worry about it.

Doesn't it make more sense to make your library more bundle-able and tree-shake-able to help progress the web, while still allowing people that really need to support older browsers (but having the burden on _them_ in that case)?

**Comment by whimzyLive** [comment]
@aukevanleeuwen Sorry missed the message earlier.

I am happy to take in any PRs that aim to improve the usability of the library. 
Are you able to raise a PR for that? 

Cheers.

**Comment by aukevanleeuwen** [comment]
@whimzyLive, no worries. I did have a look at it, but have no experience with your build system. [Your `tsconfig` looks reasonable](https://github.com/typedorm/typedorm/blob/72fb5094c2201373dcc5dfec47f9308637ee44b2/tsconfig.json#L14). But apparently somewhere in the Bazel build system this will be rewritten. I can't really pinpoint exactly where, but I think this issue says something similar: https://github.com/bazelbuild/rules_nodejs/issues/122.

I did find https://stackoverflow.com/questions/65598485/how-should-i-invoke-webpack-to-bundle-bazels-ts-library-output, which seems to imply that this can be changed though.

I tinkered around with bazel, tried to upgrade it as well (you have a rather old version) but that got me into a rabbithole that - unfortunately - I don't have time for. Since we are just starting up a project and this is blocking progress we will for now try with [a different library](https://github.com/jeremydaly/dynamodb-toolbox).

Thanks again for your efforts of providing this though!

**Comment by perrin4869** [comment]
I think one of the challenges here will be the still missing `nodenext` and `node12` module support in `typescript` which seems like will be finally added in `4.7`... but in the meantime, it will be hard to output an `esm` module because `typescript` will get rid of the `.js` extensions for imports, and those are required by the `node.js` esm loader...

**Comment by mathieubrd** [comment]
Hello,
We switched to TypeDORM for our AWS Lambdas. We are completly stuck because TypeDORM is using UMD instead of CJS or EMD. We have to use esbuild to bundle our Lambdas, which is a blocking point with TypeDORM because of UMD.

I think @aukevanleeuwen is right here. TypeDORM should not be bundled using UMD anymore. It's obviously an issue for a lot of people.

**Comment by whimzyLive** [comment]
@mathieubrd 
This will be get resolved soon and will be available in the Beta channel, latest by the end of the week next week.

Meanwhile, I would suggest skipping the TypeDORM packages from the bundle and installing it as external modules, when running in Lambda.

**Comment by danieljarrett74** [comment]
@whimzyLive 

Just checking in on this.  Did this get added to beta?

Same as @mathieubrd I'm stuck on this too.  I've tried the latest beta

package.json
```    
    "@typedorm/common": "^1.15.0-beta.5",
    "@typedorm/core": "^1.15.0-beta.5",

```

and still getting the reported error:

```

Error: Cannot find module '@typedorm/common/public-api'
...
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by whimzyLive** [comment]
@danieljarrett74 This is not implemented yet. Make you have subscribed to this thread for the latest updates.

**Comment by danieljarrett74** [comment]
> @danieljarrett74 This is not implemented yet. Make you have subscribed to this thread for the latest updates.
Thanks @whimzyLive.  

Reason I was asking was because you mentioned it will be on the Beta channel a few weeks back.  Is it still something that is coming in the near future?  Just wondering if I should hold out or looks for work arounds.

> This will get resolved soon and will be available in the Beta channel, latest by the end of the week next week.
> 
> Meanwhile, I would suggest skipping the TypeDORM packages from the bundle and installing it as external modules, when running in Lambda.

**Comment by danieljarrett74** [comment]
@mathieubrd or @aldex32  did you figure out a workaround to this?

I've tried the webpack example provided by @whimzyLive and this seems to successfully exclude these files from the package.   

```
module.exports = {
  ... // other config
  module: {
    noParse: /@typedorm\/[core|common|testing]/
  },
};
```

But what I'm now stuck on,  and I'm sure this is more of a standard webpack question but I've been going around in circles for an entire day now.  How do I now use webpack to include the unbundled @typedorm files in my output folder so my lambda will run?

**Comment by whimzyLive** [comment]
@danieljarrett74 
I am not sure if webpack is able to do that for you, but what you will need to do is have another build step before publishing artifacts to lambda 
Here you will need to 
- copy pacakge.json to the dist/artifact directory 
- run npm install to install it as an external dependency.

This way when you publish the artifacts to lambda, it will contain your bundled js file along with node_modules containing @typedorm/* packages.  

May I ask how are you publishing code to lambda?

**Comment by danieljarrett74** [comment]
@whimzyLive 

I'm using terraform. 

Thanks for that.  I got it to work by making a modified package.json that only included the typedorm modules.  If I included all my node modules the lambda zip would be too large.

**Comment by TheMechanic** [comment]
Hi, I have this problem in a serverless project, using esbuild for building. But it's fine, just add the package to the exclude prop of esbuild module, then everything will be run :)

**Comment by refactorthis** [comment]
@whimzyLive thanks for looking into this. I am also having this issue, currently using the layer workaround from @TheMechanic
