### ISSUE TITLE
Duplicate GSI attribute (sortKey) preventing create, but valid in AWS

### ISSUE THREAD

**Issue by tylerthardy** [typedorm/typedorm#228]
### Expectation
An entity can have two GSIs that use the same sortKey in AWS. TypeDORM should allow two GSIs with the same sortKey.

Are we using DDB or TypeDORM improperly?

### Issue
We receive the following error when attempting to create via EntityManager:
```
    Failed to parse entity "testEntity", duplicate attribute "time".

      at ../core/src/classes/transformer/base-transformer.ts:110:19
          at Array.forEach (<anonymous>)
      at ../core/src/classes/transformer/base-transformer.ts:108:41
          at Array.reduce (<anonymous>)
      at DocumentClientRequestTransformer.toDynamoEntity (../core/src/classes/transformer/base-transformer.ts:102:57)
      at DocumentClientRequestTransformer.toDynamoPutItem (../core/src/classes/transformer/document-client-request-transformer.ts:134:31)
      at EntityManager.<anonymous> (../core/src/classes/manager/entity-manager.ts:157:55)
      at node_modules/@typedorm/core/src/classes/manager/entity-manager.js:7:71
```

### Code for Reproduction
**NOTE**: We can bypass the error by removing the 2nd and 3rd indexes in the Entity annotation, leaving only 1 GSI.

AWS GSI configuration:
![image](https://user-images.githubusercontent.com/17709869/160635198-bde0140d-a36f-420c-a6cc-e73a733d60f4.png)

Table configuration:
```TypeScript
const table = new Table({
  name: 'table-name',
  partitionKey: 'id',
  sortKey: 'time',
  indexes: {
    'id-property1-index': {
      type: INDEX_TYPE.GSI,
      partitionKey: 'id_property1',
      sortKey: 'time' //<-- same sortKey as other indexes
    },
    'id-property1-property2-index': {
      type: INDEX_TYPE.GSI,
      partitionKey: 'id_property1_property2',
      sortKey: 'time' //<-- same sortKey as other indexes
    },
    'id-property2-index': {
      type: INDEX_TYPE.GSI,
      partitionKey: 'id_property2',
      sortKey: 'time' //<-- same sortKey as other indexes
    }
  }
});
```

Entity configuration:
```TypeScript
@Entity<TestEntity>({
  name: 'testEntity',
  primaryKey: {
    partitionKey: '{{id}}',
    sortKey: '{{time}}'
  },
  indexes: {
    'id-property1-index': {
      type: INDEX_TYPE.GSI,
      partitionKey: '{{id}}#{{property1}}',
      sortKey: '{{time}}'
    },
    'id-property1-property2-index': {
      type: INDEX_TYPE.GSI,
      partitionKey: '{{id}}#{{property1}}#{{property2}}',
      sortKey: '{{time}}'
    },
    'id-property2-index': {
      type: INDEX_TYPE.GSI,
      partitionKey: '{{id}}#{{property2}}',
      sortKey: '{{time}}'
    }
  }
})
export class TestEntity {
  @Attribute()
  id!: string;

  @Attribute()
  time!: string;

  @Attribute()
  property1!: string;

  @Attribute()
  property2!: number;

  @Attribute()
  property3!: string;

  @Attribute()
  id_property1?: string;

  @Attribute()
  id_property1_property2?: string;

  @Attribute()
  id_property2?: string;
}

```

**Comment by tylerthardy** [comment]
Updated the original issue to better reflect the problem. It's an issue with the create method on EntityManager, not creating a connection.

Added additional note about how we can get it to behave as expected.

**Comment by whimzyLive** [comment]
@tylerthardy 
Good question,

Generally, when you are working with a single-table design pattern within DynamoDB, it is advised to not reuse the same attribute for multiple indexes, and this library is built to follow and make users follow the best practices.

Therefore it is not possible to reuse the same exact attribute for multiple indexes. In fact, the TypeDORM will not instantiate a connection to DynamoDB, which will give you an error like the one you are seeing.

The Ideal way to implement your entity (when working with multiple indexes in general), you want to have your table declared like this

```typescript
const table = new Table({
  name: 'table-name',
  partitionKey: 'id',
  sortKey: 'time',
  indexes: {
    'id-property1-index': {
      type: INDEX_TYPE.GSI,
      partitionKey: 'id-property1-index-pk',
      sortKey: 'id-property1-index-sk' 
    },
    'id-property1-property2-index': {
      type: INDEX_TYPE.GSI,
      partitionKey: 'id-property1-property2-index-pk',
      sortKey: 'id-property1-property2-index-sk' 
    },
    'id-property2-index': {
      type: INDEX_TYPE.GSI,
      partitionKey: 'id-property2-index-pk',
      sortKey: 'id-property2-index-sk' 
    }
  }
});
```   
and entity can be the same.

This basically allows you to have an independent copy of attributes for each index, which will be managed by TypeDORM.

The thing to note here is that, when you define unique `partionKey` and `sortKey` for each index, your data will et duplicated across all the indexes for those attributes.
i.e the value of attribute `time` from main table will get duplicated to all three index sort keys -   `id-property1-index-sk`, `id-property1-property2-index-sk` and `id-property2-index-sk`. 

For more examples on working with TypeDORM have a look at the [TypeDORM Guide](https://github.com/typedorm/typedorm/blob/main/docs/guide.md)

**Comment by whimzyLive** [comment]
Closing this as there is no plan to change this behavior. 

If you still think there are certain scenarios where this is useful, please feel free to reopen the issue.

**Comment by MightySepp666** [comment]
@whimzyLive first at all thanks for your great work on this project!

But I totally disagree with you on this topic. Can you please state where you found the information, that using the same sort key for multiple GSI is considered bad practice? If read through and searched the official docs (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/best-practices.html) multiple times, but couldn't find anything related (same for a Google search). 

As far as I know, it's actually a widespread pattern to use the partition key as sort key in secondary indexes. I even consider it a bad practice for a library/framework to put up restrictions, that are not necessary or don't make sense regarding the underlying infrastructure. Especially as it makes it very hard to migrate existing projects that rely on these features.

My current use case (which I would consider pretty straight-forward) is currently not possible with this restriction:
- I store entities, that have a relation to other entities: a widget referencing an entity that is displayed
- I already have a global secondary index to query widgets by another attribute, that is using the widget ID as sort key
- Now I would also like to query the widgets for a certain entity. The obvious and easiest way is to add another GSI that uses the referenced entities ID as partition key and the widget ID as sort key (multiple widgets can be created for the same entity)
=> But now I receive this irritating error

In the current architecture, there is no way to enforce consistency for the duplicated attributes, that would all contain the partition key (widget ID). I can't use a default value transformation, because the ID is obviously part of the key (and index) and default values are not supported for these attributes. Since there is also no way to perform model specific computations before updates (e.g. by triggers/events), I would be forced to move the code to duplicate the ID outside of the entity class, which obviously violates basic OOP principles.

Please let me know your thoughts about this.
