### ISSUE TITLE
proposal: testing in v3

### ISSUE THREAD

**Issue by jensbodal** [typedorm/typedorm#251]
Was working to get a similar test pattern setup for v3 and came up with this:

```
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { createMock } from '@golevelup/ts-jest';
import { ConnectionManager, ConnectionOptions, Container, createConnection } from '@typedorm/core';
import { DocumentClientV3 } from '@typedorm/document-client';

export function createTestConnection(connectionOptions: Omit<ConnectionOptions, 'documentClient'>) {
  const documentClient = new DocumentClientV3(createMock<DynamoDBClient>());
  return createConnection({ ...connectionOptions, documentClient });
}

export function resetTestConnection() {
  Container.get(ConnectionManager).clear();
}
```

I then am using it like this (key parts of setup and usage):

```
import { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';
import { mockClient } from 'aws-sdk-client-mock';

describe('my-test-suite', () => {
  const ddbMock = mockClient(DynamoDBDocumentClient);

  const connection = createTestConnection({
    entities: [ExportEntity],
    table: new MyTable(),
  });

  beforeEach(async () => {
    resetTestConnection();
    ddbMock.reset();
    jest.resetAllMocks();
  });

  // inside a test... 
  it('tests stuff', () => {
    ddbMock.callsFake(() => ({
      Items: [
        {
          id: uuid,
        }
      ]
    });
  });
});
```

Figured I would just throw this out there, not really sure if it’s the right path for this lib since I’m using both `@golevelup/ts-jest` and `aws-sdk-client-mock` which would introduce two new libs.

I have this further abstracted out a bit since I’m using NestJS and have this declared with a module, but it’s essentially what I’m doing now.

**Comment by whimzyLive** [comment]
@jensbodal Amazing, every bit of suggestion help make this library great, but we try not to introduce too many dependencies unless necessary.
In saying that tho, you could always write an extension :) 

We do plan to provide a higher level of test helpers for each TypeDORM Manager so that the consumers of this library can painlessly verify their implementation. There are some very minimal test helpers already available in `@typedorm/testing`.

 It is okay to assert the payloads sent to the document client for now, but ideally, consumers of this lib should be asserting the payloads sent to the TypeDORM managers and not the underlying document client.  
 It is TypeDORM's responsibility to ensure that enough testing is done for each transformation so that consumers can trust the lib.
 
 Closing this one for now, but keep the new ideas coming.

**Comment by jensbodal** [comment]
I was writing this more as an integration test since I’m still new to this lib and wanted to have a solid assurance that I didn’t break anything when deployed. Totally get that it’s not the right fit for this lib though :)

I think the main issue was that (unless I’m missing something) the current test module exported in beta requires AWS-sdk v2

**Comment by whimzyLive** [comment]
Yeah makes sense. 

 > I think the main issue was that (unless I’m missing something) the current test module exported in beta requires AWS-sdk v2

This sounds like a bug with the current testing module. Are you able to raise a separate issue just for that and I will have a look at it?

**Comment by jensbodal** [comment]
Sure thing, created https://github.com/typedorm/typedorm/issues/252
