### ISSUE TITLE
GSI throws error when key field allows for undefined value.

### ISSUE THREAD

**Issue by danieljarrett74** [typedorm/typedorm#313]
The error message I'm recieving below is a bit confusing so I'm guessing what is going on.  But it looks like when i define a field as being able to be undefined, then i get the following error.  As far as I understand it should be possible to have an empty GSI key field. 

 Error: \"mySecondaryId\" is used in key {{mySecondaryId}}, thus it's type must be or scalar type, if attribute type is Enum, please set \"isEnum\" to true in attribute decorator.

```
@Entity({
  name: "myentity",
  primaryKey: {
    partitionKey: "{{id}}",
    sortKey: "{{someOtherField}}",
  },
  indexes: {
    MySecondaryIdIndex: {
      type: INDEX_TYPE.GSI,
      partitionKey: '{{mySecondaryId}}',
      sortKey: '{{id}}'
    },
  },
})
```

my secondary index field is defined as follows:
```
  @Attribute()
  mySecondaryId: string | undefined;
```

**Comment by danieljarrett74** [comment]
So setting this to useEnum made the error go away,  but at the same time I also noticed that this only will work on a string field.  If you have a GSI that is a Number this will fail. 

Should this be logged as a bug?  Maybe to add an isNullable to the attribute decorator?

**Comment by whimzyLive** [comment]
For being able to set the GSI attribute to optional, you don't have to define anything special as all secondary index keys are optional by default in `DynamoDB` and `TypeDORM` both, and this behaviour is defined as [Sparse Indexes in AWS](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-indexes-general-sparse-indexes.html). 

The error you are getting is probably because of the way the attribute is referenced in the Entity schema.

When keys are made up of simple attribute values and do not have any other complex pattern structure to them, the schema should be defined as aliases of attributes on the entity, as shown below
```typescript
@Entity<TestEntity>({
  name: 'test-entity',
  table: testTable,
  primaryKey: {
    partitionKey: {
      alias: 'id',
    },
    sortKey: {
      alias: 'someOtherField',
    },
  },
  indexes: {
    GSI1: {
      type: INDEX_TYPE.GSI,
      partitionKey: {
        alias: 'mySecondaryId',
      },
      sortKey: {
        alias: 'id',
      },
      isSparse: false,
    },
  },
})
export class TestEntity {
  @Attribute()
  id: string;

  @Attribute()
  someOtherField: string;

  @Attribute()
  mySecondaryId: string | undefined;
}

```
