### ISSUE TITLE
Creating __en field in table

### ISSUE THREAD

**Issue by kikeiz** [typedorm/typedorm#334]
I am using the library and when creating a new register, it automatically adds a field "__es" with the name of the table. Is there a way to avoid that?

**Comment by whimzyLive** [comment]
Hi @kikeiz ,

No the `__en` cannot be avoided. 
It is a metadata field required to later denormalize the JSON to a model.

What's the use-case?

**Comment by kikeiz** [comment]
When scanning the database using the scan method from the scanManager I cannot retrieve the registers from the DB which has the __en field since it is not defined in the @Entity, and when I defined it, I receive an error when compiling the project: 'Attribute name "__en" is reserved by TypeDORM and cannot be used'

**Comment by whimzyLive** [comment]
The `__en` is an internal property and TypeDORM specific, these should not be declared on the entity as it is reserved by TypeDORM.

When working with Entity and Scan managers, you will never see this property in the returned response as it gets auto-truncated in the denormalization phase.  If scanning a database with something other than TypeDORM, you can manually exclude this from the returned result.

**Comment by yuliswe** [comment]
Hi @whimzyLive I'd like to help develop this library and I'm learning the code base.
I'd like to remove the `__en` from the database entirely because I believe that it can simply be added after the data is fetched from the DB and before the object is transformed into a class. Is that something you believe is possible?
