### ISSUE TITLE
TypeDORM not autogenerating attributes when creating or updating entities

### ISSUE THREAD

**Issue by MurylloEx** [typedorm/typedorm#338]
I'm encountering an error while using TypeDORM library in TypeScript. The error message is as follows:

```
C:\Users\Muryllo\desktop\packages\core\src\helpers\parse-key.ts:33
    return key.replace(regexExp.interpolation, substr => {
               ^
Error: "pk" was referenced in SURL#{{pk}} but it's value could not be resolved.
    at C:\Users\Muryllo\desktop\packages\core\src\helpers\parse-key.ts:48:23
    at String.replace (<anonymous>)
    at parseKey (C:\Users\Muryllo\desktop\packages\core\src\helpers\parse-key.ts:33:16)
    at C:\Users\Muryllo\desktop\packages\core\src\classes\transformer\base-transformer.ts:327:30
    at Array.reduce (<anonymous>)
    at DocumentClientRequestTransformer.recursiveParseEntity (C:\Users\Muryllo\desktop\packages\core\src\classes\transformer\base-transformer.ts:319:46)
    at DocumentClientRequestTransformer.toDynamoEntity (C:\Users\Muryllo\desktop\packages\core\src\classes\transformer\base-transformer.ts:98:35)
    at DocumentClientRequestTransformer.toDynamoPutItem (C:\Users\Muryllo\desktop\packages\core\src\classes\transformer\document-client-request-transformer.ts:136:31)
    at EntityManager.<anonymous> (C:\Users\Muryllo\desktop\packages\core\src\classes\manager\entity-manager.ts:207:55)
    at Generator.next (<anonymous>)
```

The error occurs in a TypeScript code that uses the TypeDORM library, specifically in the parseKey function in the parse-key.ts file. The error indicates that there was an attempt to reference the "pk" key in a string template, but the value of this key could not be resolved. The error occurs during code execution, specifically when creating an item of the ShortUrl entity using the create() method of the entityManger object. The complete source code that produces the error is included in the issue message.

`Imports`
```ts
import 'reflect-metadata';
import { createConnection } from '@typedorm/core';
import { DocumentClientV3 } from '@typedorm/document-client';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { 
  Table, 
  Attribute,
  Entity,
  AutoGenerateAttribute,
  AUTO_GENERATE_ATTRIBUTE_STRATEGY
} from '@typedorm/common';
```

`Table`
```ts
export const TableShortUrl = new Table({
  name: 'ShortUrl',
  partitionKey: 'pk',
  sortKey: 'sk'
});
```

`Entity definition`
```ts
@Entity({
  name: 'short_url',
  primaryKey: {
    partitionKey: 'SURL#{{pk}}',
    sortKey: 'SURL#{{code}}',
  }
})
export class ShortUrl {

  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.UUID4
  })
  public pk!: string;

  @Attribute()
  public code!: string;

  @Attribute()
  public url!: string;

  @Attribute({ default: 0 })
  public accessCount!: number;

  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.EPOCH_DATE,
    autoUpdate: true
  })
  public createdAt!: number;

  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.EPOCH_DATE,
    autoUpdate: true
  })
  public updatedAt!: number;

}
```

`Creating the connection`
```ts
(async () => {
  const documentClient = new DocumentClientV3(new DynamoDBClient({
    endpoint: 'http://localhost:6800'
  }));

  const connection = createConnection({
    table: TableShortUrl,
    entities: [ShortUrl],
    documentClient,
  });

  const entityManger = connection.entityManager;

  const shortUrl = new ShortUrl();

  //shortUrl.pk = '0000000'
  //shortUrl.createdAt = +new Date
  //shortUrl.updatedAt = +new Date
  shortUrl.accessCount = 1;
  shortUrl.code = 'aDFJ3kjf2'
  shortUrl.url = 'https://google.com/';

  // create item
  const response = await entityManger.create<ShortUrl>(shortUrl);

  // get item
  const retrieved = await entityManger.findOne(ShortUrl, {
    pk: response.pk,
    accessCount: 1
  });

  console.log(retrieved);

  // delete item
  await entityManger.delete(ShortUrl, {
    pk: response.pk,
    accessCount: 1
  });
})();
```

Am I doing something wrong? I followed the GitHub guide faithfully with some minor modifications.

**Comment by ryok90** [comment]
Stumbled across this and found the solution to my problem on [another issue](https://github.com/typedorm/typedorm/issues/236).

> @danieljarrett74 I believe it could be happening due to the "target" property set to be the latest - "es2022" in the `tsconfig.json`.
> 
> The TypeDORM relies on `reflect-metadata to properly expose runtime metadata which I believe is not working correctly with the latest ES2022/next target.
> 
> Can you try with a lower version? Maybe `es2021`?

Leaving this here for future reference.

**Comment by eremzeit** [comment]
I was having a similar issue.  In my case, it came down to the behavior of the compiler flag `useDefineForClassFields`. The root issue is that TypeDORM only assigns autogenerated values to attributes don't have any key defined on the entity object.    (see the `toDynamoEntity` method on `BaseTransformer`) 

Suppose you have this code. 
```
@Entity({name: 'FooEntity'})
export class FooEntity {
  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.UUID4,
  })
  id: string;
}

console.log(new FooEntity())
```

 If `useDefineForClassFields` is false, then there will be a completely empty object.  But if it's true, then you'll have an object with `{id: undefined}`.  If you were to try to use typedorm to save the object with `entityManager.create(new FooEntity())` then this would fail error because the `id` attribute is `undefined`.  

The workaround would be either to 1) set `useDefineForClassFields` to false in your tsconfig, or to 2) manually strip your entities of any undefined fields before passing them to `entityManager.create(entity)`.

In targets of es2022 and later (including esnext), this flag defaults to true.  In the default settings in a nextjs 13 starter app, the target is `es5` so the flag defaults to false.  So if you're a nextjs user, you're not likely to run into this issue.  I hit the issue though when I setup vitest.  Vite uses esbuild, which doesn't support decorators.  So modified vite.config.ts to use SWR for builds, but for some reason SWR isn't honoring the value of `useDefineForClassFields`.  

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

**Comment by eremzeit** [comment]
Created an issue to support future versions of typescript defaults https://github.com/typedorm/typedorm/issues/368

**Comment by strongpauly** [comment]
I'm still seeing this error with `useDefineForClassFields` = false.  My tsconfig compiler options are:
```
{
        "allowSyntheticDefaultImports": true,
        "baseUrl": "./",
        "declaration": true,
        "esModuleInterop": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "incremental": true,
        "lib": ["ES2022", "DOM"],
        "module": "Node16",
        "moduleResolution": "Node16",
        "outDir": "./dist",
        "removeComments": true,
        "resolvePackageJsonExports": true,
        "sourceMap": true,
        "skipLibCheck": true,
        "target": "ES2022",
        "useDefineForClassFields": false
 }
``` 
I realise there are issues with a target of ES2022, but without #365 occurs.  Is there an actual workaround?
